### ISSUE TITLE
Connect to Event Hub-compatible endpoint of Azure iot hub failed due to EventHubAuthCBS Status Failed

### ISSUE THREAD

**Issue by luyaok** [Azure/azure-event-hubs-c#12] opened 2017-04-05 08:23 UTC
I use Receive sample:
https://github.com/Azure/azure-event-hubs-c/tree/master/eventhub_client/samples/receive

And edit it to connect to Event Hub-compatible endpoint of Azure iot hub to receive Device-To-Cloud messages.

```
static const char* connectionString = "Endpoint=[MY Event Hub-compatible endpoint];SharedAccessKeyName=service;SharedAccessKey=[MY SharedAccessKeyValue]";
static const char* eventHubPath     = "messages/events";
static const char* consumerGroup    = "$Default"; //example "$Default"
static const char* partitionId      = "0";        //example "0"
```

After running I get the following error information:

> Error: Time:Wed Apr  5 16:15:39 2017 File:C:\Users\v-luhan\Downloads\azure-event-hubs-c-master\azure-event-hubs-c-master\eventhub_client\src\eventhubreceiver_ll.c Func:_HandleSASTokenAuth Line:264 EventHubAuthCBS Status Failed.

**Comment by dcristoloveanu** [comment] 2017-04-11 06:34
@luyaok 
Sorry for the delay in answering.
I believe the issue is with the fact that the eventHubPath must be the compatible eventhub name (it should be the same as the IoTHub name).

I will close this issue, but let me know if this does not solve the problem that you had.

Thanks,
/Dan

**Closed by dcristoloveanu** 2017-04-11 06:34 UTC
